/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Application;

import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Jorismar
 */
public class CustomAverageFilterWindow extends javax.swing.JFrame {

    /**
     * Creates new form CustomAverageFilter
     */
    public CustomAverageFilterWindow() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon("resrc/img/app_icon.png").getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        input_num_columns = new javax.swing.JTextField();
        button_ok = new javax.swing.JButton();
        input_num_lines = new javax.swing.JTextField();
        button_cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jLabel1.setText("Tamanho da Matriz");

        jLabel3.setText("X");

        input_num_columns.setForeground(new java.awt.Color(153, 153, 153));
        input_num_columns.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        input_num_columns.setText("Colunas");
        input_num_columns.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_num_columnsFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_num_columnsFocusLost(evt);
            }
        });
        input_num_columns.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                input_num_columnsKeyPressed(evt);
            }
        });

        button_ok.setText("OK");
        button_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_okActionPerformed(evt);
            }
        });

        input_num_lines.setForeground(new java.awt.Color(153, 153, 153));
        input_num_lines.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        input_num_lines.setText("Linhas");
        input_num_lines.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_num_linesFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_num_linesFocusLost(evt);
            }
        });

        button_cancel.setText("Cancelar");
        button_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel1)
                            .addComponent(button_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(input_num_lines, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(input_num_columns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(button_cancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(input_num_columns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(input_num_lines, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_ok)
                .addGap(0, 0, 0)
                .addComponent(button_cancel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_okActionPerformed
        try {
            this.numLines = Integer.parseInt(this.input_num_lines.getText());
            this.numColumns = Integer.parseInt(this.input_num_columns.getText());
            
            if (this.numLines == 0 || this.numColumns == 0)
                JOptionPane.showMessageDialog(this, "Os valores devem ser maiores que zero.", "Erro", JOptionPane.ERROR_MESSAGE);
            else
                this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Valor inválido!\nVerifique os valores digitados e tente novamente!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_button_okActionPerformed

    private void input_num_linesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_num_linesFocusLost
        if (this.input_num_lines.getText().length() == 0) {
            this.input_num_lines.setForeground(new java.awt.Color(153, 153, 153));
            this.input_num_lines.setText("Linhas");
        }
    }//GEN-LAST:event_input_num_linesFocusLost

    private void input_num_linesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_num_linesFocusGained
        this.input_num_lines.setForeground(new java.awt.Color(0, 0, 0));
        this.input_num_lines.setText("");
    }//GEN-LAST:event_input_num_linesFocusGained

    private void input_num_columnsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_num_columnsFocusGained
        this.input_num_columns.setForeground(new java.awt.Color(0, 0, 0));
        this.input_num_columns.setText("");
    }//GEN-LAST:event_input_num_columnsFocusGained

    private void input_num_columnsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_num_columnsFocusLost
        if (this.input_num_columns.getText().length() == 0) {
            this.input_num_columns.setForeground(new java.awt.Color(153, 153, 153));
            this.input_num_columns.setText("Colunas");
        }
    }//GEN-LAST:event_input_num_columnsFocusLost

    private void button_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cancelActionPerformed
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_button_cancelActionPerformed

    private void input_num_columnsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_input_num_columnsKeyPressed
        if (evt.getKeyCode() == 10)
            this.button_okActionPerformed(null);
    }//GEN-LAST:event_input_num_columnsKeyPressed

    public int getNumLines() {
        return numLines;
    }

    public int getNumColumns() {
        return numColumns;
    }
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomAverageFilterWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomAverageFilterWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomAverageFilterWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomAverageFilterWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomAverageFilterWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_cancel;
    private javax.swing.JButton button_ok;
    private javax.swing.JTextField input_num_columns;
    private javax.swing.JTextField input_num_lines;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
    private int numLines = 0;
    private int numColumns = 0;
}
